const API_KEY = import.meta.env.VITE_TMDB_KEY

const requests = {
  fetchTrending: `/trending/all/week?api_key=${API_KEY}&language=en-US`,
  fetchNetflixOriginals: `/discover/tv?api_key=${API_KEY}&with_networks=213`,
  fetchTopRated: `/movie/top_rated?api_key=${API_KEY}&language=en-US`,
  fetchActionMovies: `/discover/movie?api_key=${API_KEY}&with_genres=28`,
  fetchComedyMovies: `/discover/movie?api_key=${API_KEY}&with_genres=35`,
  fetchHorrorMovies: `/discover/movie?api_key=${API_KEY}&with_genres=27`,
  fetchRomanceMovies: `/discover/movie?api_key=${API_KEY}&with_genres=10749`,
  fetchDocumentaries: `/discover/movie?api_key=${API_KEY}&with_genres=99`,
  fetchTV: `/discover/tv?api_key=${API_KEY}&with_genres=10765`,
  fetchTopTV: `/tv/top_rated?api_key=${API_KEY}&language=en-US`,
  fetchPopularTV: `/tv/popular?api_key=${API_KEY}&language=en-US`,
  fetchOnTheAirTV: `/tv/on_the_air?api_key=${API_KEY}&language=en-US`,
  fetchAiringTodayTV: `/tv/airing_today?api_key=${API_KEY}&language=en-US`,
  fetchMovieDetails: `/movie/{movie_id}?api_key=${API_KEY}&language=en-US`,
  fetchTVDetails: `/tv/{tv_id}?api_key=${API_KEY}&language=en-US`,
  fetchSearchMovie: `/search/movie?api_key=${API_KEY}&language=en-US&query=`,
  fetchSearchTV: `/search/tv?api_key=${API_KEY}&language=en-US&query=`,
  fetchPerson: `/person/{person_id}?api_key=${API_KEY}&language=en-US`,
  fetchPersonMovies: `/person/{person_id}/movie_credits?api_key=${API_KEY}&language=en-US`,
  fetchPersonTV: `/person/{person_id}/tv_credits?api_key=${API_KEY}&language=en-US`,
  fetchMovieCast: `/movie/{movie_id}/credits?api_key=${API_KEY}&language=en-US`,
  fetchTVCast: `/tv/{tv_id}/credits?api_key=${API_KEY}&language=en-US`,
  fetchMovieReviews: `/movie/{movie_id}/reviews?api_key=${API_KEY}&language=en-US`,
  fetchTVReviews: `/tv/{tv_id}/reviews?api_key=${API_KEY}&language=en-US`,
  fetchMovieVideos: `/movie/{movie_id}/videos?api_key=${API_KEY}&language=en-US`,
  fetchTVVideos: `/tv/{tv_id}/videos?api_key=${API_KEY}&language=en-US`,
  fetchMovieRecommendations: `/movie/{movie_id}/recommendations?api_key=${API_KEY}&language=en-US`,
  fetchTVRecommendations: `/tv/{tv_id}/recommendations?api_key=${API_KEY}&language=en-US`,
  fetchMovieSimilar: `/movie/{movie_id}/similar?api_key=${API_KEY}&language=en-US`,
  fetchTVSimilar: `/tv/{tv_id}/similar?api_key=${API_KEY}&language=en-US`,
  fetchMovieLists: `/movie/{movie_id}/lists?api_key=${API_KEY}&language=en-US`,
  fetchTVLists: `/tv/{tv_id}/lists?api_key=${API_KEY}&language=en-US`,
  fetchMovieAccountStates: `/movie/{movie_id}/account_states?api_key=${API_KEY}&language=en-US`,
  fetchTVAccountStates: `/tv/{tv_id}/account_states?api_key=${API_KEY}&language=en-US`,
  fetchMovieWatchlist: `/account/{account_id}/lists?api_key=${API_KEY}&language=en-US`,
  fetchTVWatchlist: `/account/{account_id}/lists?api_key=${API_KEY}&language=en-US`,
  fetchMovieWatchlistDetails: `/list/{list_id}?api_key=${API_KEY}&language=en-US`,
}

export default requests;
